### ISSUE TITLE
Setting Up Environment Variables | Database conf

### ISSUE THREAD

**Issue by hugohernani** [edddjunior/my-ruby-repo#2]
The development workflow goes through some different environment. The most common types are:
- TEST: automated tests like Unit tests are done in the environment;
- DEVELOPMENT: This is the Dev machine environment. The dev has its own settings for accessing its services, databases, etc;
- STAGE: This is the environment to be displayed across team and client. It's not the "ready to use" environment. Therefore, the users' client won't have access to it, preferably.
- PRODUCTION: This is the final environment. Most of its settings are boosted to meet client required performance. So, as instance. In DEV (even STAGE) we can use **puma** web server but on Production we ended with something like **unicorn**, since we expect that unicorn can server files "better" than puma. We also usually wrap things up on Production environment. So, css, javascript, all assets are pre-processed and loaded as a package to be served faster in Production.

After understanding some basic differences between environments it's good to know about environment variables.

Each environment has some variables related to it only. And this goes beyond deployment environment. We can differ environment variable by developer machine.
So, at DEVELOPMENT environment we can have a var that says the name of the DATABASE the project is attached to. But to avoid conflicts with already existing DATABASE on developer machine we **allow** the to say which env var is better for it.

Going practical, let's analyse this file: https://github.com/edddjunior/my-ruby-repo/blob/master/config/database.yml

You are saying that to access the database the developer should have a postgres user called `pguser` but I don't have this user and I would like to use another one: i.e. `pg_hugo` user.

To work with this kind of customization you can do as follow:
```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST"){ localhost } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
```

To apply this settings the dev usually has to start the project with the following command: `DB_USER=pg_hugo DB_PASSWORD=12341234 bundle exec rails server`. But fortunately there are some gems that helps us with that. One of them is: https://github.com/bkeepers/dotenv.

You can also use **Rails Secrets** (check link in the comment below) to set custom values to some configuration file. Example:
```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
```

This issue is for settings up **dontenv** and using env vars on `config/database.yml` file.
LMK if you have questions in the comments section.
